bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: pWYsO/oqx0zUy9/ZM+f2NPJ6TZGTJqX/Q8kzaGm6GeWg7rSBW0ynCStEyInsg9iCgHpFXbCKMbpZFwGpoUB9znsbSLLU+U6LhXj9jbfsrNsP/w3UtmLHhysKtgfM6PDYQZpqotqL0lCCwNpUjt1uFbY3ROW+KPzgsS/RE/tPLHhecuI9IjcWJg/lJ6ktv7/hZOYJ2KFxkK0/6EB9z/+3Zs4PZw8mZstJCnvQkJsbEIhhIHWMLJaK3bwBXHiqp11bkLW+vCsf999bQljXsleJvMwytjRIOA58jITaVHyYcn4tuL4fG45ZATerglkiwSn6x0dyoRS5Jn3pCsbMT5oaNC1xpEKNn7Po6D/+gYBt1oWng2XvE2fJRr49wjW9jixRGLs2JOjWKRbrOevQ1wFb+coaAQV2uo0aCWiPZT5A7JXmrucB2nSRYuCKphItKkV1XDAUDhC5W9rKqRd/7dYRje6tIegm8TGuVoSl+G2qr16FT89aHRSafzLNf3byMROkmnJidB/yRQxYaR0LbWBKSwTjo84S/6NeA4qvvRVtVwf1vs27Kpc3S5ngnes11DpVCSrrl4Iutmdp4oHQm7P0RgRgAmyVFIk/8cyzMIxIfEnPIAzAeQr5f8m79Q8CR+uS7jStiPa30nnwSEx6gCfs12jj8j5DbeONOVSdvMw30bk=
conda_forge_output_validation: true
